SAM_STEP = 60
SAM_TRESH = 0.25

BLUR_SPREAD = 101.0
MAX_IMAGE_EDGE = 640
DILATION_SCALE = 1.0
VECTOR_EMA_ALPHA = 0.3
DIRECTION_EMA_ALPHA_MIN = 0.1
DIRECTION_EMA_ALPHA_MAX = 0.8
EXCLUSION_ANGLE_DEGREES = 60.0
MAX_OBSERVED_COVERAGE_RATIO = 0.25
COVERAGE_LOOKAHEAD_SECONDS = 2.0

SEGMENTATION_CLUSTER_DISTANCE_THRESHOLD = 50
